services:
    '@enhavo/translation/form/loader/TranslationLoader':
        chunk: 'form'
        arguments:
            - '@enhavo/app/frame/EventDispatcher'
        tags:
            - 'enhavo_app.form'
